<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JenisPekerjaanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Data contoh untuk jenis pekerjaan
        $data = [
            ['kode' => '0002', 'jenis_pekerjaan' => 'PEGAWAI NEGERI'],
            ['kode' => '0001', 'jenis_pekerjaan' => 'SWASTA'],
            ['kode' => '0003', 'jenis_pekerjaan' => 'KARYAWAN BANK'],
            ['kode' => '0004', 'jenis_pekerjaan' => 'TNI'],
            ['kode' => '0005', 'jenis_pekerjaan' => 'POLISI'],
            ['kode' => '0006', 'jenis_pekerjaan' => 'PETANI'],
            ['kode' => '0007', 'jenis_pekerjaan' => 'PEDAGANG'],
            ['kode' => '0008', 'jenis_pekerjaan' => 'KARYAWAN SWASTA'],
            ['kode' => '0009', 'jenis_pekerjaan' => 'GURU'],
            ['kode' => '0010', 'jenis_pekerjaan' => 'TUKANG BANGUNAN'],
            ['kode' => '0011', 'jenis_pekerjaan' => 'PENGRAJIN'],
            ['kode' => '0012', 'jenis_pekerjaan' => 'KARYAWAN PABRIK'],
            ['kode' => '0013', 'jenis_pekerjaan' => 'SATPAM'],
            ['kode' => '0014', 'jenis_pekerjaan' => 'OJEK'],
            ['kode' => '0015', 'jenis_pekerjaan' => 'PENSIUNAN'],
            ['kode' => '0016', 'jenis_pekerjaan' => 'KONTRAKTOR'],
            ['kode' => '0017', 'jenis_pekerjaan' => 'MEBEL'],
            ['kode' => '0018', 'jenis_pekerjaan' => 'SOPIR'],
            ['kode' => '0019', 'jenis_pekerjaan' => 'BENGKEL'],
            ['kode' => '0020', 'jenis_pekerjaan' => 'POTONG RAMBUT'],
            ['kode' => '0021', 'jenis_pekerjaan' => 'TUKANG KAYU'],
            ['kode' => '0022', 'jenis_pekerjaan' => 'PEDAGANG TEBU'],
            ['kode' => '0023', 'jenis_pekerjaan' => 'PT.MULTI BREDER'],
            ['kode' => '0024', 'jenis_pekerjaan' => 'dagang sayur'],
            ['kode' => '0025', 'jenis_pekerjaan' => 'TOUR & TRAVEL'],
            ['kode' => '0026', 'jenis_pekerjaan' => 'DAGANG PANGSIT'],
            ['kode' => '0027', 'jenis_pekerjaan' => 'PENGRAJIN ROTAN'],
            ['kode' => '0028', 'jenis_pekerjaan' => 'PEDAGANG BUAH'],
            ['kode' => '0029', 'jenis_pekerjaan' => 'KARY. PT LANGGENG JAYA'],
            ['kode' => '0030', 'jenis_pekerjaan' => 'KARY.PT SAFFANA DIANDRA BERSAUDARA'],
            ['kode' => '0031', 'jenis_pekerjaan' => 'KARY. GATRA MAPAN'],
            ['kode' => '0032', 'jenis_pekerjaan' => 'DAGANG AYAM POTONG'],
            ['kode' => '0033', 'jenis_pekerjaan' => 'PERHUTANI'],
            ['kode' => '0034', 'jenis_pekerjaan' => 'JURU PARKIR'],
            ['kode' => '0035', 'jenis_pekerjaan' => 'KARY HSBC'],
            ['kode' => '0036', 'jenis_pekerjaan' => 'KARY UD PARAMA NATAJAYA'],
            ['kode' => '0037', 'jenis_pekerjaan' => 'USAHA KRUPUK'],
            ['kode' => '0038', 'jenis_pekerjaan' => 'KARY SUMBER RASA'],
            ['kode' => '0039', 'jenis_pekerjaan' => 'PT AGRO DANA FUTURE'],
            ['kode' => '0040', 'jenis_pekerjaan' => 'PT INDUSTRI SANDANG NUSANTARA'],
            ['kode' => '0041', 'jenis_pekerjaan' => 'SERVICE DINAMO MOTOR LISTRIK'],
            ['kode' => '0042', 'jenis_pekerjaan' => 'PEMBORONG'],
            ['kode' => '0043', 'jenis_pekerjaan' => 'PLIZER GLOBAL PHARMACEUTICALS'],
            ['kode' => '0044', 'jenis_pekerjaan' => 'PT BINTANG MAS'],
            ['kode' => '0045', 'jenis_pekerjaan' => 'HAKSA PRINT SABLON'],
            ['kode' => '0046', 'jenis_pekerjaan' => 'PENJAHIT'],
            ['kode' => '0047', 'jenis_pekerjaan' => 'KARY PT ISPEKPINDO PRATAMA'],
            ['kode' => '0048', 'jenis_pekerjaan' => 'KARY LAWANG INDAH LESTARI'],
            ['kode' => '0049', 'jenis_pekerjaan' => 'PT BENTOEL'],
            ['kode' => '0050', 'jenis_pekerjaan' => 'KARY. ADI PUTRO'],
            ['kode' => '0051', 'jenis_pekerjaan' => 'Pegawai Unmuh'],
            ['kode' => '0052', 'jenis_pekerjaan' => 'KARY PT WONOKOYO'],
            ['kode' => '0053', 'jenis_pekerjaan' => 'DAGANG KOMPUTER'],
            ['kode' => '0054', 'jenis_pekerjaan' => 'PT RODA MAS'],
            ['kode' => '0055', 'jenis_pekerjaan' => 'PT TOMBAK AMPUH'],
            ['kode' => '0056', 'jenis_pekerjaan' => 'PG KEBON AGUNG'],
            ['kode' => '0057', 'jenis_pekerjaan' => 'PT SUKORENTEX'],
            ['kode' => '0058', 'jenis_pekerjaan' => 'IBU RUMAH TANGGA'],
            ['kode' => '0059', 'jenis_pekerjaan' => 'konveksi'],
            ['kode' => '0060', 'jenis_pekerjaan' => 'KARY SIDOBANGUN'],
            ['kode' => '0061', 'jenis_pekerjaan' => 'KARY SEQUISLIFE'],
            ['kode' => '0062', 'jenis_pekerjaan' => 'KARY HOTEL SANTIKA'],
            ['kode' => '0063', 'jenis_pekerjaan' => 'DOKTER GIGI'],
            ['kode' => '0064', 'jenis_pekerjaan' => 'PERIAS'],
            ['kode' => '0065', 'jenis_pekerjaan' => 'TUKANG BATU'],
            ['kode' => '0066', 'jenis_pekerjaan' => 'KARY ESTERENTEX'],
            ['kode' => '0067', 'jenis_pekerjaan' => 'PETERNAKAN'],
            ['kode' => '0068', 'jenis_pekerjaan' => 'PENGACARA'],
            ['kode' => '0069', 'jenis_pekerjaan' => 'DOSEN'],
            ['kode' => '0070', 'jenis_pekerjaan' => 'KARY KAROSERI MORODADI'],
            ['kode' => '0071', 'jenis_pekerjaan' => 'KARY PT NISSIN MAS'],
            ['kode' => '0072', 'jenis_pekerjaan' => 'JUAL-BELI MOBIL'],
            ['kode' => '0073', 'jenis_pekerjaan' => 'TUKANG KAYU'],
            ['kode' => '0074', 'jenis_pekerjaan' => 'KARY PATAL'],
            ['kode' => '0075', 'jenis_pekerjaan' => 'PERANGKAT DESA'],
            ['kode' => '0076', 'jenis_pekerjaan' => 'TUKANG CAT'],
            ['kode' => '0077', 'jenis_pekerjaan' => 'ANSURANSI AJINDO'],
            ['kode' => '0078', 'jenis_pekerjaan' => 'KARY OPTIK'],
            ['kode' => '0079', 'jenis_pekerjaan' => 'KARY PT RISKA'],
            ['kode' => '0080', 'jenis_pekerjaan' => 'SANGGAR SENAM'],
            ['kode' => '0081', 'jenis_pekerjaan' => 'DAGANG BESI TUA'],
            ['kode' => '0082', 'jenis_pekerjaan' => 'KARY PT BORWITA CITRA PRIMA'],
            ['kode' => '0083', 'jenis_pekerjaan' => 'KARY PT PESONA REMAJA'],
            ['kode' => '0084', 'jenis_pekerjaan' => 'KARY RUMAH SAKIT ISLAM'],
            ['kode' => '0085', 'jenis_pekerjaan' => 'TOKO ANEKA JAYA'],
            ['kode' => '0086', 'jenis_pekerjaan' => 'SALES'],
            ['kode' => '0087', 'jenis_pekerjaan' => 'MAHASISWA'],
            ['kode' => '0088', 'jenis_pekerjaan' => 'SERVICE AC'],
            ['kode' => '0089', 'jenis_pekerjaan' => 'KARY ARGO WISATA'],
            ['kode' => '0090', 'jenis_pekerjaan' => 'KARY TAMBAK UDANG'],
            ['kode' => '0091', 'jenis_pekerjaan' => 'TRAVEL'],
            ['kode' => '0092', 'jenis_pekerjaan' => 'DAGANG BAKSO'],
            ['kode' => '0093', 'jenis_pekerjaan' => 'SERVICE ELEKTRONIK'],
            ['kode' => '0094', 'jenis_pekerjaan' => 'KARY PT. BSW'],
            ['kode' => '0095', 'jenis_pekerjaan' => 'KARY PANTAI FOTO'],
            ['kode' => '0096', 'jenis_pekerjaan' => 'KARY PT. RCI'],
            ['kode' => '0097', 'jenis_pekerjaan' => 'KARY PT RAJA WIRA SAKTI'],
            ['kode' => '0098', 'jenis_pekerjaan' => 'JUAL BELI SEPEDA MOTOR'],
            ['kode' => '0099', 'jenis_pekerjaan' => 'KARY. PT MORODADI'],
            ['kode' => '0100', 'jenis_pekerjaan' => 'MANDOR BANGUNAN'],
            ['kode' => '0101', 'jenis_pekerjaan' => 'KARY. PT. DUPONT'],
            ['kode' => '0102', 'jenis_pekerjaan' => 'KARY. CV. CAT COMPUTER'],
            ['kode' => '0103', 'jenis_pekerjaan' => 'KARY. PT MOLINDO RAYA INDUSTRIAL'],
            ['kode' => '0104', 'jenis_pekerjaan' => 'PERCETAKAN'],
            ['kode' => '0105', 'jenis_pekerjaan' => 'KARY. PT. HERO'],
            ['kode' => '0106', 'jenis_pekerjaan' => 'BIRO JASA DLLAJR'],
            ['kode' => '0107', 'jenis_pekerjaan' => 'KARY. PT. PANDE PANGAN PARTIKA'],
            ['kode' => '0108', 'jenis_pekerjaan' => 'PENGGILINGAN BATU'],
            ['kode' => '0109', 'jenis_pekerjaan' => 'KARY. PT. SINGOSARI'],
            ['kode' => '0110', 'jenis_pekerjaan' => 'KARY. PT. ARTHA WENA'],
            ['kode' => '0111', 'jenis_pekerjaan' => 'RENTAL STUDIO MUSIK'],
            ['kode' => '0112', 'jenis_pekerjaan' => 'ANTAR JEMPUT'],
            ['kode' => '0113', 'jenis_pekerjaan' => 'KARY. DAMRI'],
            ['kode' => '0114', 'jenis_pekerjaan' => 'RENTAL PS'],
            ['kode' => '0115', 'jenis_pekerjaan' => 'KONSULTAN'],
            ['kode' => '0116', 'jenis_pekerjaan' => 'KARY. PT. ATRI'],
            ['kode' => '0117', 'jenis_pekerjaan' => 'KARY. RS MARSUDI WALUYO'],
            ['kode' => '0118', 'jenis_pekerjaan' => 'KARY. KOPERASI NASIONAL'],
            ['kode' => '0119', 'jenis_pekerjaan' => 'SELEP PADI'],
            ['kode' => '0120', 'jenis_pekerjaan' => 'KARY PT. K A I'],
            ['kode' => '0121', 'jenis_pekerjaan' => 'Pembantu Rumah tangga'],
            ['kode' => '0122', 'jenis_pekerjaan' => 'TUKANG PIJAT'],
            ['kode' => '0123', 'jenis_pekerjaan' => 'KARY. CV. ADIKARYA'],
            ['kode' => '0124', 'jenis_pekerjaan' => 'KARY. RM WAPU'],
            ['kode' => '0125', 'jenis_pekerjaan' => 'INSTALATIR LISTRIK'],
            ['kode' => '0126', 'jenis_pekerjaan' => 'USAHA GYPSE'],
            ['kode' => '0127', 'jenis_pekerjaan' => 'KARY. PT. BORNEO'],
            ['kode' => '0128', 'jenis_pekerjaan' => 'KARY PT PUTERA INDO PERKASA'],
            ['kode' => '0129', 'jenis_pekerjaan' => 'KARY. PT INDIRATEX'],
            ['kode' => '0130', 'jenis_pekerjaan' => 'KARY. HOTEL GRAHA CAKRA'],
            ['kode' => '0131', 'jenis_pekerjaan' => 'KARY. DLLAJR'],
            ['kode' => '0132', 'jenis_pekerjaan' => 'KARY. PT UMC'],
            ['kode' => '0133', 'jenis_pekerjaan' => 'KARY. PT KARYA DUTA'],
            ['kode' => '0134', 'jenis_pekerjaan' => 'KARY. PT. INDOMARINE'],
            ['kode' => '0135', 'jenis_pekerjaan' => 'KARY. PT MULTIBREDEER'],
            ['kode' => '0136', 'jenis_pekerjaan' => 'KARY. PT PERDANA BODY REPAIR'],
            ['kode' => '0137', 'jenis_pekerjaan' => 'KARY. PT ARAYA'],
            ['kode' => '0138', 'jenis_pekerjaan' => 'KARY. PT ARTO MORO'],
            ['kode' => '0139', 'jenis_pekerjaan' => 'MATRIALAN'],
            ['kode' => '0140', 'jenis_pekerjaan' => 'KARY. PT. WONOSARI AGUNG'],
            ['kode' => '0141', 'jenis_pekerjaan' => 'SABLON'],
            ['kode' => '0142', 'jenis_pekerjaan' => 'KARY. PT OTSUKA INDONESIA'],
            ['kode' => '0143', 'jenis_pekerjaan' => 'KARY. PT. SARIAYU'],
            ['kode' => '0144', 'jenis_pekerjaan' => 'RENTAL KOMPUTER'],
            ['kode' => '0145', 'jenis_pekerjaan' => 'KARY. SEKOLAH SLB'],
            ['kode' => '0146', 'jenis_pekerjaan' => 'KARY. CV DIAN PUTRA'],
            ['kode' => '0147', 'jenis_pekerjaan' => 'KARY. PT BDF'],
            ['kode' => '0148', 'jenis_pekerjaan' => 'KARY. PDAM'],
            ['kode' => '0149', 'jenis_pekerjaan' => 'KARY. PLAZA ELEKTRO'],
            ['kode' => '0150', 'jenis_pekerjaan' => 'KARY. PT. UNGGUL'],
            ['kode' => '0151', 'jenis_pekerjaan' => 'KARY PT ONIX'],
            ['kode' => '0152', 'jenis_pekerjaan' => 'PEMBUATAN BATU BATA'],
            ['kode' => '0153', 'jenis_pekerjaan' => 'KARY. PO PAHALA KENCANA'],
            ['kode' => '0154', 'jenis_pekerjaan' => 'KARY KOPERASI'],
            ['kode' => '0155', 'jenis_pekerjaan' => 'KARY. PHILIP MORES'],
            ['kode' => '0156', 'jenis_pekerjaan' => 'KARY. PT JATI MAS'],
            ['kode' => '0157', 'jenis_pekerjaan' => 'PENGRAJIN KLOMPEN'],
            ['kode' => '0158', 'jenis_pekerjaan' => 'POLRI'],
            ['kode' => '0159', 'jenis_pekerjaan' => 'HOME INDUSTRI'],
            ['kode' => '0160', 'jenis_pekerjaan' => 'TOKO BANGUNAN'],
            ['kode' => '0161', 'jenis_pekerjaan' => 'KARY. UD. TARUNA JAYA'],
            ['kode' => '0162', 'jenis_pekerjaan' => 'KARY FIF'],
            ['kode' => '0163', 'jenis_pekerjaan' => 'PERSEWAAN SOUND SISTEM'],
            ['kode' => '0164', 'jenis_pekerjaan' => 'STUDIO FOTO'],
            ['kode' => '0165', 'jenis_pekerjaan' => 'LAUNDRY'],
            ['kode' => '0166', 'jenis_pekerjaan' => 'DISTRIBUTOR ALAT-ALAT TERAPI'],
            ['kode' => '0167', 'jenis_pekerjaan' => 'karyawan koperasi'],
            ['kode' => '0168', 'jenis_pekerjaan' => 'KARY. PT PANAH MAS'],
            ['kode' => '0169', 'jenis_pekerjaan' => 'KARY PT SOEDALI SEJAHTERA'],
            ['kode' => '0170', 'jenis_pekerjaan' => 'KARY. PT RANDI CONES INDONESIA'],
            ['kode' => '0171', 'jenis_pekerjaan' => 'KARY. UD KARTO MOTOR'],
            ['kode' => '0172', 'jenis_pekerjaan' => 'KARY. PAJAK CAB BATU'],
            ['kode' => '0173', 'jenis_pekerjaan' => 'KARY. ACC'],
            ['kode' => '0174', 'jenis_pekerjaan' => 'KARY. PT RAJAWALI'],
            ['kode' => '0175', 'jenis_pekerjaan' => 'KARY GAS EQUIPMENT'],
            ['kode' => '0176', 'jenis_pekerjaan' => 'KARY. PT BINTANG TERANG'],
            ['kode' => '0177', 'jenis_pekerjaan' => 'KARY. PT. SAMPOERNA'],
            ['kode' => '0178', 'jenis_pekerjaan' => 'KARY PADANG GOLF'],
            ['kode' => '0179', 'jenis_pekerjaan' => 'PEDAGANG MAS'],
            ['kode' => '0180', 'jenis_pekerjaan' => 'PENGGILINGAN PADI'],
            ['kode' => '0181', 'jenis_pekerjaan' => 'KARY. UNISMA'],
            ['kode' => '0182', 'jenis_pekerjaan' => 'KARY PT SRIGUNTING'],
            ['kode' => '0183', 'jenis_pekerjaan' => 'KARY CIPTA KARYA ABADI'],
            ['kode' => '0184', 'jenis_pekerjaan' => 'GM JAWA POS'],
            ['kode' => '0185', 'jenis_pekerjaan' => 'PENGGOSOAN BATU PERMATA'],
            ['kode' => '0186', 'jenis_pekerjaan' => 'KONDEKTUR'],
            ['kode' => '0187', 'jenis_pekerjaan' => 'IBU RUMAH TANGGA'],
            ['kode' => '0188', 'jenis_pekerjaan' => 'KARY PT. TJKA'],
            ['kode' => '0189', 'jenis_pekerjaan' => 'GARMEN'],
            ['kode' => '0190', 'jenis_pekerjaan' => 'KARY PIALA MAS'],
            ['kode' => '0191', 'jenis_pekerjaan' => 'KRY PT MULTI KREASI'],
            ['kode' => '0192', 'jenis_pekerjaan' => 'KARY.CV WARIATI'],
            ['kode' => '0193', 'jenis_pekerjaan' => 'KARY. KACANG BAYI'],
            ['kode' => '0194', 'jenis_pekerjaan' => 'KARY. PT INTERNIT KERANG'],
            ['kode' => '0195', 'jenis_pekerjaan' => 'KARY. JASA TIRTA'],
            ['kode' => '0196', 'jenis_pekerjaan' => 'KARY. PT PILAR MAS MANDIRI'],
            ['kode' => '0197', 'jenis_pekerjaan' => 'KARY. PT PAR'],
            ['kode' => '0198', 'jenis_pekerjaan' => 'USAHA KOS KOSAN'],
            ['kode' => '0199', 'jenis_pekerjaan' => 'KARY MEBEL PT.NATANIA'],
            ['kode' => '0200', 'jenis_pekerjaan' => 'KARY. KSP INSAN MANDIRI'],
            ['kode' => '0201', 'jenis_pekerjaan' => 'CV SETIA PRATIWI'],
            ['kode' => '0202', 'jenis_pekerjaan' => 'KARY. PT GTM'],
            ['kode' => '0203', 'jenis_pekerjaan' => 'LAUNDRY PARADISE'],
            ['kode' => '0204', 'jenis_pekerjaan' => 'KARY. PT MAYA UTAMA'],
            ['kode' => '0205', 'jenis_pekerjaan' => 'KARY. SAND PRODUCTION'],
            ['kode' => '0206', 'jenis_pekerjaan' => 'JASA ANGKUTAN'],
            ['kode' => '0207', 'jenis_pekerjaan' => 'KEPALA DESA'],
            ['kode' => '0208', 'jenis_pekerjaan' => 'KARY. PT GABRIELE'],
            ['kode' => '0209', 'jenis_pekerjaan' => 'KARY. PT ORANG TUA'],
            ['kode' => '0210', 'jenis_pekerjaan' => 'KARY. PT DIAMOND'],
            ['kode' => '0211', 'jenis_pekerjaan' => 'USAHA TEMPE'],
            ['kode' => '0212', 'jenis_pekerjaan' => 'KARY. PT TRISAKTI'],
            ['kode' => '0213', 'jenis_pekerjaan' => 'KARY. PT PODOJOYO MANSYUR'],
            ['kode' => '0214', 'jenis_pekerjaan' => 'KARY. PT ETIRA'],
            ['kode' => '0215', 'jenis_pekerjaan' => 'VIDEOGRAFER'],
            ['kode' => '0216', 'jenis_pekerjaan' => 'KARY. PT MINATEX'],
            ['kode' => '0217', 'jenis_pekerjaan' => 'SABLON'],
            ['kode' => '0218', 'jenis_pekerjaan' => 'TUKANG BECAK'],
            ['kode' => '0219', 'jenis_pekerjaan' => 'USAHA KRIPIK TEMPE'],
            ['kode' => '0220', 'jenis_pekerjaan' => 'TEKNIK MESIN'],
            ['kode' => '0221', 'jenis_pekerjaan' => 'KARY GUNTORMISRI SENTOSA'],
            ['kode' => '0222', 'jenis_pekerjaan' => 'SALON KECANTIKAN'],
            ['kode' => '0223', 'jenis_pekerjaan' => 'KARY HAPPY MOTOR'],
            ['kode' => '0224', 'jenis_pekerjaan' => 'KARY KOP ARTHA KARYA MANDIRI'],
            ['kode' => '0225', 'jenis_pekerjaan' => 'KARY KOP SADAR JAYA'],
            ['kode' => '0226', 'jenis_pekerjaan' => 'KARY ASURANSI BUMI PUTERA'],
            ['kode' => '0227', 'jenis_pekerjaan' => 'DEPOT'],
            ['kode' => '0228', 'jenis_pekerjaan' => 'KARY COURTS MALANG'],
            ['kode' => '0229', 'jenis_pekerjaan' => 'PEGAWAI NEGERI SIPIL'],
            ['kode' => '0230', 'jenis_pekerjaan' => 'DAGANG BUNGA'],
            ['kode' => '0231', 'jenis_pekerjaan' => 'KARY RS PANCA DARMA'],
            ['kode' => '0232', 'jenis_pekerjaan' => 'BURUH'],
            ['kode' => '0234', 'jenis_pekerjaan' => 'KARY UNMER'],
            ['kode' => '0235', 'jenis_pekerjaan' => 'KARY UNMUH']
        ];

        // Memasukkan data ke dalam tabel "jenis_pekerjaan"
        foreach ($data as $item) {
            DB::table('jenis_pekerjaan')->insert($item);
        }
    }
}
